自己用的CentOs8,阿里云上有自动部署mysql的镜像


https://help.aliyun.com/document_detail/188447.html
配置文件：/etc/my.cnf
数据存储：/var/lib/mysql
命令文件：/usr/bin和/usr/sbin



步骤一：安装MySQL
远程连接CentOS 8系统的ECS实例。
具体操作，请参见通过密码或密钥认证登录Linux实例。
切换CentOS 8源地址。
CentOS 8操作系统版本结束了生命周期（EOL），按照社区规则，CentOS 8的源地址http://mirror.centos.org/centos/8/内容已移除，您在阿里云上继续使用默认配置的CentOS 8的源会发生报错。如果您需要使用CentOS 8系统中的一些安装包，则需要手动切换源地址。具体操作，请参见CentOS 8 EOL如何切换源？。

运行以下命令安装MySQL。
dnf -y install @mysql
安装完成后，运行以下命令查看MySQL版本信息。
mysql -V
查看版本结果如下图所示。mysql 8.0.21
步骤二：配置MySQL
运行以下命令启动MySQL，并设置为开机自启动。
systemctl enable --now mysqld
运行以下命令查看MySQL是否已启动。
systemctl status mysqld
查看返回结果中Active: active (running)表示已启动。
运行以下命令执行MySQL安全性操作并设置密码。
mysql_secure_installation
命令运行后，根据命令行提示执行如下操作。
输入Y并回车开始相关配置。
选择密码验证策略强度，输入2并回车。
策略0表示低，1表示中，2表示高。建议您选择高强度的密码验证策略。

设置MySQL的新密码并确认。
本示例设置密码PASSword123！。

输入Y并回车继续使用提供的密码。
输入Y并回车移除匿名用户。
输入Y并回车禁止root用户远程连接MySQL。
输入Y并回车删除test库以及对test库的访问权限。
输入Y并回车重新加载授权表。
步骤三：远程访问MySQL数据库
建议您使用非root账号远程登录MySQL数据库。本示例中，将创建新的MySQL用户账户，用于远程访问MySQL。

为ECS实例所属的安全组入方向放行MySQL所需的端口号。
MySQL默认占用的端口号为3306。您需要在ECS实例所使用的安全组入方向添加规则并放行3306端口。具体步骤，请参见添加安全组规则。
在ECS实例上，创建并配置远程访问MySQL的账号。
运行以下命令后，输入root用户的密码登录MySQL。
 mysql -uroot -p
在MySQL客户端中，依次运行以下命令，创建用于远程访问MySQL的账号，并允许远程主机使用该账号访问MySQL。
本示例中，账号为dms、密码为PASSword123!。
create user 'dms'@'%' identified by 'PASSword123!';
grant all privileges on *.* to 'dms'@'%'with grant option;
flush privileges;
说明 实际创建账号时，密码需符合要求。长度为8至30个字符，必须同时包含大小写英文字母、数字和特殊符号。可以使用以下特殊符号：
()` ~!@#$%^&*-+=|{}[]:;‘<>,.?/

使用dms账号远程登录MySQL。
（推荐）您可以通过阿里云提供的数据管理服务DMS（Data Management Service）来远程访问MySQL数据库。详细信息，请参见云数据库录入。
您可以通过本地主机的远程连接工具进行测试。例如：MySQL Workbench、Navicat。



不过这里自己想自己部署一下

引用  https://www.cnblogs.com/fanshudada/p/9781794.html
1系统约定
安装文件下载目录：/data/software
Mysql目录安装位置：/usr/local/mysql
数据库保存位置：/data/mysql
日志保存位置：/data/log/mysql


2下载mysql

在官网：http://dev.mysql.com/downloads/mysql/ 中，选择以下版本的mysql下载：

执行如下命名：
#mkdir /data/software
#cd /data/software

--下载安装包 

--建议：在windows上使用迅雷下载，速度很快（我的是1M/s），然后用工具（Xftp）上传到 /data/software目录下；
#wget http://dev.mysql.com/get/Downloads/MySQL-5.7/mysql-5.7.17-linux-glibc2.5-x86_64.tar.gz

3解压压缩包到目标位置

#cd /data/software

--解压压缩包

#tar -xzvf /data/software/mysql-5.7.17-linux-glibc2.5-x86_64.tar.gz

--移动并修改文件名

#mv /data/software/mysql-5.7.17-linux-glibc2.5-x86_64 /usr/local/mysql

4创建数据仓库目录

--/data/mysql 数据仓库目录
# mkdir /data/mysql         
#ls /data/



5新建mysql用户、组及目录
#      ---新建一个msyql组
# useradd -r -s /sbin/nologin -g mysql mysql -d /usr/local/mysql     ---新建msyql用户禁止登录shell

6改变目录属有者

#cd /usr/local/mysql
#pwd
#chown -R mysql .
#chgrp -R mysql .



#chown -R mysql /data/mysql

7配置参数
# bin/mysqld --initialize --user=mysql --basedir=/usr/local/mysql --datadir=/data/mysql



 此处需要注意记录生成的临时密码，如上文结尾处的：YLi>7ecpe;YP
#bin/mysql_ssl_rsa_setup  --datadir=/data/mysql

 

8修改系统配置文件

#cd /usr/local/mysql/support-files



# cp my-default.cnf /etc/my.cnf
# cp mysql.server /etc/init.d/mysql

# vim /etc/init.d/mysql

修改以下内容：



9启动mysql

# /etc/init.d/mysql start

--登陆

# mysql -hlocalhost -uroot -p

　　--如果出现：-bash: mysql: command not found

　　--就执行： # ln -s /usr/local/mysql/bin/mysql /usr/bin --没有出现就不用执行

--输入第6步生成的临时密码

--修改密码

mysql> set password=password('root');

--设置root账户的host地址（修改了才可以远程连接）

mysql>grant all privileges on *.* to 'root'@'%' identified by 'root';
mysql>flush privileges;

--查看表

mysql> use mysql;
mysql> select host,user from user;

--这里就可以使用远程连接测试了；



 

如提示不能成功连接，可能需要添加需要监听的端口

/sbin/iptables -I INPUT -p tcp --dport 3306 -j ACCEPT

 

10添加系统路径
# vim /etc/profile
添加：
export PATH=/usr/local/mysql/bin:$PATH
如下：



# source /etc/profile

11配置mysql自动启动
# chmod 755 /etc/init.d/mysql
# chkconfig --add mysql
# chkconfig --level 345 mysql on

以上就是linux环境Mysql 5.7.13安装教程，希望对大家的学习有所帮助。

 

补充：

--退出mysql命令窗口

#exit

 --查看mysql状态

#service mysql status

--停止mysql

#service mysql stop

--启动mysql

#service mysql start

 

 

附my.cnf（这是一个配置mysql配置文件，暂时可以不用管，如你想钻研 你可以百度或google “mysql my.cnf 配置详情”）

/etc/my.cnf
# For advice on how to change settings please see
# http://dev.mysql.com/doc/refman/5.7/en/server-configuration-defaults.html
# *** DO NOT EDIT THIS FILE. It's a template which will be copied to the
# *** default location during install, and will be replaced if you
# *** upgrade to a newer version of MySQL.

[mysqld]

# Remove leading # and set to the amount of RAM for the most important data
# cache in MySQL. Start at 70% of total RAM for dedicated server, else 10%.
innodb_buffer_pool_size = 10G

# Remove leading # to turn on a very important data integrity option: logging
# changes to the binary log between backups.
log_bin
character-set-server=utf8
collation-server=utf8_bin
init-connect='SET NAMES utf8'
# These are commonly set, remove the # and set as required.
basedir = /usr/local/mysql
datadir = /export/mysql/var
port = 3306
server_id = 22206
socket = /export/mysql/mysql.sock
binlog_format = statement
# Remove leading # to set options mainly useful for reporting servers.
# The server defaults are faster for transactions and fast SELECTs.
# Adjust sizes as needed, experiment to find the optimal values.
join_buffer_size = 128M
sort_buffer_size = 2M
read_rnd_buffer_size = 2M
log_bin_trust_function_creators = on
sql_mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES

lower_case_table_names=1